token = "Wyltrh3idQ0Aio86" # API token for lichess
botname = "slinky-bot" # Name of the bot account
url = "https://lichess.org/api/" # Url for lichess api

[engine]
path = "/home/angel/go/src/hugo/hugo" # Path to uci compatible engine
#   [engine.options]
#   threads = 1 # Number of CPU threads to use
#   hash = 512 # Max memory in MB engine can use
#   [engine.go]
#   nodes = 1 # Search number of nodes only
#   depth = 5 # Search depth limit
#   movetime = 5000 # Move time limit in milliseconds

[network]
latency = 100 # Estimated network latency when sending requests in milliseconds

[challenge]
variants = [ # Variants engine supports
  "standard"
]
speeds = [ # Speeds to play at
  "blitz",
  "bullet"
]
modes = [ # Modes to play. Must be "rated" and/or "casual"
  "rated",
  "casual"
]